// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2BcVhoYywaOn1_sRU9ueNLKmORnf_nYA',
    appId: '1:317521341923:web:2c70491283cfed4cd044d6',
    messagingSenderId: '317521341923',
    projectId: 'city-3e469',
    authDomain: 'city-3e469.firebaseapp.com',
    storageBucket: 'city-3e469.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw6SB8pOzu4PQFrvfP5h4KoF32nsKNhAk',
    appId: '1:317521341923:android:b6ec356cbb27d5dfd044d6',
    messagingSenderId: '317521341923',
    projectId: 'city-3e469',
    storageBucket: 'city-3e469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsapoTZh9Shq0UPa1lDUxtqX1qUhSGKd4',
    appId: '1:317521341923:ios:2ddcdf48d8cfc246d044d6',
    messagingSenderId: '317521341923',
    projectId: 'city-3e469',
    storageBucket: 'city-3e469.appspot.com',
    iosBundleId: 'com.example.herafiApp',
  );
}
